// ──────────────────────────────────────────────────────
// Canonical CRM lead row (maps 1-to-1 to crm_leads)
// ──────────────────────────────────────────────────────

export type LeadSource = "meta" | "linkedin" | "chatbot";
export type LeadStage =
  | "lead"
  | "new"
  | "contacted"
  | "qualified"
  | "proposal"
  | "won"
  | "lost";

export interface CrmLead {
  id?: string; // UUID – generated by Supabase
  name: string;
  title: string;
  email: string;
  phone: string;
  source: LeadSource;
  stage: LeadStage;
  created_at?: string; // ISO-8601 – defaults to now()
  interest: string;
  chat_topic: string;
  cited: string[];
  notes: string;
  lost: boolean;
}

export type CrmLeadInsert = Omit<CrmLead, "id" | "created_at">;

// ──────────────────────────────────────────────────────
// Facebook / Meta webhook shapes
// ──────────────────────────────────────────────────────

export interface MetaFieldData {
  name: string;
  values: string[];
}

export interface MetaLeadPayload {
  leadgen_id: string;
  form_id?: string;
  page_id?: string;
  field_data: MetaFieldData[];
}

export interface MetaWebhookEntry {
  id: string;
  time: number;
  changes: Array<{
    field: string;
    value: MetaLeadPayload;
  }>;
}

export interface MetaWebhookBody {
  object: string;
  entry: MetaWebhookEntry[];
}

// ──────────────────────────────────────────────────────
// LinkedIn webhook shapes
// ──────────────────────────────────────────────────────

export interface LinkedInLeadPayload {
  name?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  emailAddress?: string;
  phone?: string;
  phoneNumber?: string;
  company?: string;
  companyName?: string;
  jobTitle?: string;
  title?: string;
  [key: string]: unknown;
}

// ──────────────────────────────────────────────────────
// Chatbot webhook shapes
// ──────────────────────────────────────────────────────

export interface ChatbotLeadPayload {
  name?: string;
  email?: string;
  phone?: string;
  interest?: string;
  chat_topic?: string;
  notes?: string;
  [key: string]: unknown;
}

// ──────────────────────────────────────────────────────
// Generic API response envelope
// ──────────────────────────────────────────────────────

export interface ApiResponse<T = unknown> {
  success: boolean;
  message: string;
  data?: T;
  error?: string;
}